[build]
command = """
apt-get update \
  && apt-get install -y zlib1g-dev libjpeg-dev \
  && pip install --no-cache-dir -r requirements.txt \
  && python manage.py collectstatic --no-input
"""

[release]
command = "python manage.py migrate --no-input"