# Generated by Django 2.0.2 on 2020-10-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20201010_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
