# Generated by Django 2.0.2 on 2020-10-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
