# Generated by Django 3.1 on 2020-10-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_delete_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
