# Generated by Django 3.1 on 2020-10-31 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_delete_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
